// Generated by CoffeeScript 1.7.1
(function() {
  var Firebase, fs, title;

  Firebase = require("firebase");

  fs = require("fs");

  title = "Cloud";

  exports.index = function(req, res) {
    return res.render("index", {
      title: title
    });
  };

  exports.test_api = function(req, res) {
    var file, info, obj, ref, search, value, version;
    value = req.params.data;
    version = req.originalUrl.split("/")[2];
    search = req.query;
    delete search["__proto__"];
    file = "public/javascripts/config.json";
    console.log("Testing...");
    obj = JSON.parse(fs.readFile(file, "utf8"));
    ref = new Firebase(obj.db).child("api/test");
    info = {
      value: value,
      version: version,
      search: search
    };
    ref.push(info);
    console.log(info);
    return res.redirect("/#/?data=" + value);
  };

  exports.partials = function(req, res) {
    return res.render("partials/" + req.params.name, {
      title: title
    });
  };

}).call(this);
